title: PseudoLab [Let-Biostat-Guidance-Guide-Us]
author: PseudoLab
logo: 'PseudoLab_logo.png'

# Short description about the book
description: >-
  A Introduction to Biostat Guidance.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  favicon: 'PseudoLab_logo.png'
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/Pseudo-Lab/Let-Biostat-Guidance-Guide-Us
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
