title : Let Biostat Guidance Guide Us
author: Let Biostat Guidance Guide Us Team
logo: 'PseudoLab_logo.png'

# Short description about the book
description: >-
  A brief introduction to Biostat Guidance

execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/Pseudo-Lab/Let-Biostat-Guidance-Guide-Us
  path_to_book                : "mini_book"

html:
    favicon: 'PseudoLab_logo.png'
    use_issues_button: true
    use_repository_button: true
exclude_patterns: [draft/*]

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
