title: PseudoLab [Let Biostat Guidance Guide Us]
author: PseudoLab
logo: 'PseudoLab_logo.png'

# Short description about the book
description: >-
  Introduction to Biostat Guidance

execute:
  execute_notebooks           : off
  
# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url: https://github.com/pseudo-lab/Let-Biostat-Guidance-Guide-Us
  path_to_book: "book" 
  
html:
  favicon: 'PseudoLab_logo.png'
  use_issues_button: true
  use_repository_button: true
binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
exclude_patterns: [draft/*]